### PR TITLE
'Maintenance' section: `tlmgr.bat` needed on windows

### PR DESCRIPTION
**Pull request by tfiers**

### CODE REVIEW

**Comment by yihui** [comment]
I remember that for `.exe` and `.bat` files, we don't need the file extensions when executing them, but my Windows experience was from several years ago, so I might be wrong. Also in R I'm just calling `tlmgr` without the `.bat` extension: https://github.com/rstudio/tinytex/blob/c4dd1e47197856169bf1dd0ed2185fc8d772524f/R/tlmgr.R#L52 No one has reported problems over the years.

@cderv Could you verify whether the `.bat` extension is necessary when executing the `tlmgr` command? Thanks!

**Comment by cderv** [comment]
On Windows, I don't need the extensions. I have TeX Live binaries path setup in PATH. 

In powershell 

````powershell
> tlmgr --version
tlmgr revision 63068 (2022-04-18 07:58:07 +0200)
tlmgr using installation: C:/Users/chris/AppData/Roaming/TinyTeX
TeX Live (https://tug.org/texlive) version 2022

> Get-Command tlmgr

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     tlmgr.bat                                          0.0.0.0    C:\Users\chris\AppData\Roaming\TinyTeX\bin\win32\tlmgr.bat
````

nor in CMD, 

````
>tlmgr --version
tlmgr revision 63068 (2022-04-18 07:58:07 +0200)
tlmgr using installation: C:/Users/chris/AppData/Roaming/TinyTeX
TeX Live (https://tug.org/texlive) version 2022

>where tlmgr
C:\Users\chris\AppData\Roaming\TinyTeX\bin\win32\tlmgr.bat
````

@tfiers do you encounter any issue that requires you to set the `.bat` extension ?

**Comment by tfiers** [comment]
My bad, this is only the case in `bash.exe`! (I use bash from git-for-windows, with Windows Terminal).

`cmd.exe` and PowerShell indeed don't need the .bat extension.

Thanks for looking into it :)

**Comment by cderv** [comment]
> this is only the case in bash.exe

oh yes this is because of unix emulation terminal and `.bat` is not known there. it requires trick to call it (like adding shim `.sh` that will run the bat file.

**Pull request closed without merging**
